plt.figure(1)
plt.subplot(121)
density0 = gaussian_kde(pscore[treatment==0])
density1 = gaussian_kde(pscore[treatment==1])
xs = np.linspace(0,0.14,200)
plt.plot(xs,density0(xs),color='black')
plt.fill_between(xs,density1(xs),color='gray')
plt.text(0.03, 35, 'Control Group')
plt.text(0.06, 10, 'Treatment Group')
plt.title('Phone: Before Matching')
plt.axis([0,0.15,0,40])
plt.xlabel('Propensity Score')
plt.ylabel('Density')

plt.subplot(122)
density0_post = gaussian_kde(data_matched.pscore[data_matched.treatment==0])
density1_post = gaussian_kde(data_matched.pscore[data_matched.treatment==1])
xs = np.linspace(0,0.2,200)
plt.plot(xs,density0_post(xs),color='black')
plt.fill_between(xs,density1_post(xs),color='gray')
plt.title('Phone: After Matching')
plt.axis([0,0.15,0,40])
plt.xlabel('Propensity Score')
plt.ylabel('Density')
plt.show()